/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/layout/AppShell.vue')['default']
    BarcodeScannerPopup: typeof import('./src/components/pos/BarcodeScannerPopup.vue')['default']
    CartItem: typeof import('./src/components/pos/CartItem.vue')['default']
    CartPanel: typeof import('./src/components/pos/CartPanel.vue')['default']
    CategoryTabs: typeof import('./src/components/pos/CategoryTabs.vue')['default']
    CheckoutModal: typeof import('./src/components/pos/CheckoutModal.vue')['default']
    DailySummary: typeof import('./src/components/dashboard/DailySummary.vue')['default']
    NetworkBanner: typeof import('./src/components/layout/NetworkBanner.vue')['default']
    OrderDetail: typeof import('./src/components/order/OrderDetail.vue')['default']
    OrderList: typeof import('./src/components/order/OrderList.vue')['default']
    PaymentBreakdown: typeof import('./src/components/dashboard/PaymentBreakdown.vue')['default']
    ProductCard: typeof import('./src/components/pos/ProductCard.vue')['default']
    ProductForm: typeof import('./src/components/product/ProductForm.vue')['default']
    ProductGrid: typeof import('./src/components/pos/ProductGrid.vue')['default']
    ProductList: typeof import('./src/components/product/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/layout/SideNav.vue')['default']
    TabBar: typeof import('./src/components/layout/TabBar.vue')['default']
    TopProducts: typeof import('./src/components/dashboard/TopProducts.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
