"""add_product_barcode

Revision ID: 5ed40f2ee7bf
Revises: 700e429df1c4
Create Date: 2026-02-18 22:46:24.183512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed40f2ee7bf'
down_revision: Union[str, None] = '700e429df1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###
